wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    code_path: code/mmloc_keras.py
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.10
batch_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 10
