wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    code_path: code/sensor_baseline_keras.py
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.10
batch_size:
  desc: null
  value: 100
epochs:
  desc: null
  value: 1
hidden_size:
  desc: null
  value: 193
learning_rate:
  desc: null
  value: 0.001
output_dim:
  desc: null
  value: 2
sensor_input_size:
  desc: null
  value: 3
